#!/usr/bin/env python3.6
#
# This file is part of weatherlogd.
#
# weatherlogd is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# weatherlogd is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with weatherlogd.  If not, see <http://www.gnu.org/licenses/>.

# pylint: disable=broad-except
# pylint: disable=invalid-name

"""Periodically polls the weather sensors and inserts them into the weather database."""

import datetime
import time
import pymysql
from warwick.observatory.common import daemons

DATABASE_DB = 'ops'
DATABASE_USER = 'ops'

# Record in 5 minute steps
MEASUREMENT_BIN_SIZE = 300

# Bin zero is at ~start of 2016
MEASUREMENT_BIN_OFFSET = 4838688

ONEMETRE_VAISALA = {
    'daemon': daemons.onemetre_vaisala,
    'table': 'weather_onemetre_vaisala',
    'date_key': 'date',
    'columns': [
        'temperature', 'temperature_valid',
        'relative_humidity', 'relative_humidity_valid',
        'wind_direction', 'wind_direction_valid',
        'wind_speed', 'wind_speed_valid',
        'wind_gust', 'wind_gust_valid',
        'wind_lull', 'wind_lull_valid',
        'pressure', 'pressure_valid',
        'accumulated_rain', 'accumulated_rain_valid',
        'rain_intensity', 'rain_intensity_valid',
        'dew_point_delta', 'dew_point_delta_valid',
    ]
}

ONEMETRE_ROOMALERT = {
    'daemon': daemons.onemetre_roomalert,
    'table': 'weather_onemetre_roomalert',
    'date_key': 'date',
    'columns': ['internal_temp', 'internal_humidity', 'roomalert_temp', 'roomalert_humidity', \
        'truss_temp', 'hatch_closed', 'trap_closed', 'security_system_safe']
}

NITES_ROOMALERT = {
    'daemon': daemons.nites_roomalert,
    'table': 'weather_nites_roomalert',
    'date_key': None,
    'columns': ['internal_temperature', 'internal_humidity', 'rack_temperature', 'rack_humidity', \
        'security_system', 'mains_power']
}

GOTO_VAISALA = {
    'daemon': daemons.goto_vaisala,
    'table': 'weather_goto_vaisala',
    'date_key': 'date',
    'columns': [
        'temperature', 'temperature_valid',
        'relative_humidity', 'relative_humidity_valid',
        'wind_direction', 'wind_direction_valid',
        'wind_speed', 'wind_speed_valid',
        'wind_gust', 'wind_gust_valid',
        'wind_lull', 'wind_lull_valid',
        'pressure', 'pressure_valid',
        'accumulated_rain', 'accumulated_rain_valid',
        'rain_intensity', 'rain_intensity_valid',
        'dew_point_delta', 'dew_point_delta_valid',
    ]
}

GOTO_ROOMALERT = {
    'daemon': daemons.goto_roomalert,
    'table': 'weather_goto_roomalert',
    'date_key': 'date',
    'columns': [
        'internal_temp', 'internal_humidity', 'dome2_internal_temp', 'dome2_internal_humidity',
        'roomalert_temp', 'roomalert_humidity']
}

GOTO_DOME2_INTERNAL = {
    'daemon': daemons.rasa_internal_environment,
    'table': 'weather_goto_dome2_internal',
    'date_key': 'date',
    'columns': [
        'temperature', 'temperature_valid',
        'relative_humidity', 'relative_humidity_valid',
    ]
}

ONEMETRE_RAINDETECTOR = {
    'daemon': daemons.onemetre_rain,
    'table': 'weather_onemetre_raindetector',
    'date_key': 'date',
    'columns':  ['unsafe_boards', 'total_boards', 'port1']
}

ONEMETRE_UPS = {
    'daemon': daemons.onemetre_power,
    'table': 'weather_onemetre_ups',
    'date_key': 'date',
    'columns':  ['main_ups_status', 'main_ups_battery_remaining', 'main_ups_load', \
        'dome_ups_status', 'dome_ups_battery_remaining', 'dome_ups_load']
}

GOTO_UPS = {
    'daemon': daemons.goto_ups,
    'table': 'weather_goto_ups',
    'date_key': 'date',
    'columns':  ['main_ups_status', 'main_ups_battery_remaining', 'main_ups_load', \
        'dome_ups_status', 'dome_ups_battery_remaining', 'dome_ups_load']
}

RASA_UPS = {
    'daemon': daemons.rasa_power,
    'table': 'weather_rasa_ups',
    'date_key': 'date',
    'columns':  ['ups_status', 'ups_battery_remaining', 'ups_load']
}

SUPERWASP = {
    'daemon': daemons.superwasp_log,
    'table': 'weather_superwasp',
    'date_key': 'date',
    'columns': ['ext_temperature', 'ext_humidity', 'wind_speed', 'wind_direction', \
        'sky_temp', 'pressure', 'dew_point_delta']
}

SUPERWASP_UPS = {
    'daemon': daemons.superwasp_power,
    'table': 'weather_superwasp_ups',
    'date_key': 'date',
    'columns':  ['ups1_status', 'ups1_battery_remaining', 'ups1_load', \
        'ups2_status', 'ups2_battery_remaining', 'ups2_load', 'roofbattery']
}

SUPERWASP_ROOMALERT = {
    'daemon': daemons.superwasp_roomalert,
    'table': 'weather_superwasp_roomalert',
    'date_key': 'date',
    'columns': ['comp_room_temp', 'comp_room_humidity', 'rack_temp', 'rack_humidity', 'cam_rack_temp', 'roomalert_temp', 'roomalert_humidity', \
        'aircon_no_airflow', 'roof_closed', 'roof_power']
}

NETWORK = {
    'daemon': daemons.observatory_network_ping,
    'table': 'weather_network',
    'date_key': 'date',
    'columns': ['ngtshead', 'google', 'onemetre', 'goto', 'nites', 'swasp', 'swasp_gateway']
}

EUMETSAT_OPACITY = {
    'daemon': daemons.eumetsat_opacity,
    'table': 'weather_eumetsat_opacity',
    'date_key': 'date',
    'columns': ['opacity']
}

TNG_SEEING = {
    'daemon': daemons.tng_log,
    'table': 'weather_tng_seeing',
    'date_key': 'seeing_date',
    'columns': ['seeing']
}

ROBODIMM_SEEING = {
    'daemon': daemons.ing_robodimm,
    'table': 'weather_robodimm_seeing',
    'date_key': 'seeing_date',
    'columns': ['seeing']
}


def __run_sensor_update(sensor):
    """Reads a sensor and updates the database"""
    try:
        with sensor['daemon'].connect() as d:
            data = d.last_measurement()

        if sensor['date_key']:
            # Take date from the queried data
            date = datetime.datetime.strptime(data[sensor['date_key']], '%Y-%m-%dT%H:%M:%SZ')
        else:
            # Fall back to current date
            date = datetime.datetime.utcnow()

        # HACK: Work around missing NITES rack temperature/humidity sensor
        if 'rack_temperature' in sensor['columns']:
            data['rack_temperature'] = data['internal_temperature']
            data['rack_humidity'] = data['internal_humidity']

        # HACK: RASA dome sensor has moved to its own daemon
        if sensor['table'] == 'weather_goto_roomalert':
            data['dome2_internal_temp'] = 0
            data['dome2_internal_humidity'] = 0

        measurement_bin = int(time.mktime(date.timetuple()) / MEASUREMENT_BIN_SIZE) \
                           - MEASUREMENT_BIN_OFFSET

        default_columns = ['bin', 'date']
        default_values = [str(measurement_bin), date.strftime('"%Y-%m-%d %H:%M:%S"')]
        column_values = [db.escape(data[x]) for x in sensor['columns']]

        insert = 'REPLACE INTO ' + sensor['table'] + ' (' + ', '.join(default_columns \
            + sensor['columns']) + ') VALUES (' + ', '.join(default_values + column_values) + ');'

        with db.cursor() as cur:
            cur.execute(insert)
    except Exception as e:
        print('Failed to update ' + sensor['table'] + ' with error: ' + str(e))

if __name__ == '__main__':
    db = pymysql.connect(db=DATABASE_DB, user=DATABASE_USER, autocommit=True)
    __run_sensor_update(ONEMETRE_VAISALA)
    __run_sensor_update(ONEMETRE_ROOMALERT)
    __run_sensor_update(ONEMETRE_RAINDETECTOR)
    __run_sensor_update(ONEMETRE_UPS)
    __run_sensor_update(NITES_ROOMALERT)
    __run_sensor_update(GOTO_VAISALA)
    __run_sensor_update(GOTO_ROOMALERT)
    __run_sensor_update(GOTO_DOME2_INTERNAL)
    __run_sensor_update(GOTO_UPS)
    __run_sensor_update(SUPERWASP)
    __run_sensor_update(SUPERWASP_UPS)
    __run_sensor_update(SUPERWASP_ROOMALERT)
    __run_sensor_update(RASA_UPS)
    __run_sensor_update(NETWORK)
    __run_sensor_update(EUMETSAT_OPACITY)
    __run_sensor_update(TNG_SEEING)
    __run_sensor_update(ROBODIMM_SEEING)
